server:
  port: 8181
  servlet-path: /rest/
nebula:
  assets:
    - resourcePath: http://localhost:8081
      uriPath: /
      indexFile: index.html
      assetsName: io.nebula.admin.ui
      cached: false
      type: http # use "classpath" or "filesystem" or "http"
  quartz:
    scanPackages: [com.tr.nebula.quartz.sample]
    properties:
      org.quartz.scheduler.instanceName: QuartzScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: '1'
      org.quartz.threadPool.threadPriority: '8'
      org.quartz.scheduler.skipUpdateCheck: false
      org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
  #    org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
  #    org.quartz.jobStore.dataSource: QuarztDS
  #    org.quartz.dataSource.myDS.driver: com.mysql.jdbc.Driver
  #    org.quartz.dataSource.myDS.URL: jdbc:mysql://localhost:3306/nebula
  #    org.quartz.dataSource.myDS.user: root
  #    org.quartz.dataSource.myDS.password:
  #    org.quartz.dataSource.myDS.maxConnections: 10
  #    org.quartz.jobStore.tablePrefix: QRTZ_
  #    org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  mail:
    mailName:
      usernameKey: 'mail.smtp.username'
      passwordKey: 'mail.smtp.password'
      properties:
        mail.smtp.username: test-name
        mail.smtp.password: test-password
        mail.smtp.host: smtp.live.com
        mail.smtp.port: 25
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
