spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nebula-web-dev?useSSL=false
    username: root
    password:
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
nebula:
  assets:
    - resourcePath: ../samples/nebula-quickstart-frontend/deneme
      uriPath: /
      indexFile: index.html
      assetsName: io.nebula.admin.ui
      cached: false
      type: filesystem # use "classpath" or "filesystem" or "http"